import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import Script from 'next/script';

import { FormEventHandler, useEffect, useState } from 'react'

import { Icon } from './../componentes/Icon';

import Swal from "sweetalert2";
import styles from '../styles/Home.module.scss'

type Data = {
  id: number;
  title: string;
  image: string;
  link: string;
  requerente: string;
};

const Home: NextPage = () => {

  const [products, setProducts] = useState<Data[]>([]);
  const [productsSelecteds, setProductsSelecteds] = useState<number[]>([]);
  const [nome, setNome] = useState<string>('');
  const [sending, setSending] = useState<boolean>(false);

  const selectProduct = (i: number) => {
    if (productsSelecteds.includes(i)) {
      const copy = productsSelecteds;
      copy.splice(productsSelecteds.indexOf(i), 1);
      setProductsSelecteds([...copy]);
    } else {
      setProductsSelecteds([...productsSelecteds, i]);
    }
  }

  const formSend:FormEventHandler = async (evt) => {
    evt.preventDefault();

    if (!sending) {

      for (const productIndex of productsSelecteds) {
        const product = products[productIndex];

        const result = await fetch('/api/presente/enviar', {
          method: 'POST',
          body: JSON.stringify({
            'nome': nome,
            'id': product.id
          })
        });

        setSending(false);
      }
      setSending(true);
    }

  }

  useEffect(() => {
    fetch('/api/presente')
      .then(async response => {
        const products = await response.json();

        setProducts(products.map((product: any) => ({
          id: product.ID,
          title: product.TITULO,
          image: product.IMAGEM,
          link: product.LINK,
          requerente: product.REQUERENTE
        })));
      });
  }, []);

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Chá da Cecília</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={ styles.title }>
        <h1>
          Chá de bebê da Cecília
          <small>
            Etamos felizes com sua presença!
          </small>
        </h1>
      </div>

      <div className={ styles.mainImage }>
        <img src="images/imagem-principal.png" className={ styles.foto } />
      </div>

      <div className={ styles.segonhaImage }>
        <img src="images/segonha.png" />
      </div>

      <form onSubmit={ formSend }>


      {!nome && <div className={ styles.input }>
          <label>
            Qual o seu nome? 
          </label>

          <input 
            onBlur={(evt) => setNome(evt.currentTarget.value)}
            defaultValue={nome}
            type="text" 
            name="name"
            autoComplete="off"
            id={'name'}
            className="form-control" />

        </div>}

        {nome && <div className={ styles.nome }> 

          <strong>{ nome }</strong>, preparamos uma lista com os itens que precisamos. 

            {/* <button onClick={ () => {
              setNome("");
            }}>
              <Icon name={ 'edit' }></Icon>
            </button> */}
          </div>
        }


        <div className={styles.fixOnTop}>

          {nome.length >= 3 && <>

          { productsSelecteds.length > 0 &&
            <div className="card" id="presentes" data-fixed={false}>
              <div className="card-body">
                <strong> 
                  Seus presentes
                </strong>
                <ul>
                  { productsSelecteds.map(product => {
                    const p = products[product];
                    return <li key={product}>
                      <p>{ p.title }</p>
                      <Link href={ p.link }><a target={"_blank"}> Comprar </a></Link>
                    </li>
                  })}
                </ul>

                <button className='btn btn-default' type="submit">
                  Enviar
                </button>

              </div>
            </div>
          }

          <div className={ styles.produtos }>
          {
            products.map ((product, i) => <div className={ styles.produto } 
                key={ i } 
                data-selected={ !!product.requerente }
                data-active={ productsSelecteds.includes(i) }
                onClick={ (evt) => {
                  if (product.requerente) {
                    Swal.fire({
                      text: `${product.requerente} já escolheu esse presente.`
                    });
                    return;
                  }
                  selectProduct(i);
                  evt.stopPropagation();
                  evt.preventDefault();
                } }
              >
                <div className={ styles.moldura }>
                  <span>
                    <img src={ "images/moldura.png" } />
                  </span>
                  <div>
                    <img src={ product.image } alt={ product.title } />
                  </div>
                </div>
                <div className={ styles.productLine }>
                  {/* <span>{product.requerente}</span> */}
                  <span>{ product.title }</span>
                  <button className={ styles.btnAdicionar }> 
                    <img src={'/images/carrinho.png'} />
                    <span>Adicionar</span>
                  </button> 
                </div>
              </div>
            )
          }
          </div>

            </>
          }

        </div>



        </form>

    </div>

    <footer className={styles.footer}>
      <div className={styles.container}>
        <img src="/images/cecilia-meireles.png" alt="Cecilia Meireles" />
      </div>

      <div className={ styles.footerBar }>
        © 2022 | Todos os direitos reservados
      </div>

    </footer>

    <Script src='js/front.js' />
    </>
  )
}

export default Home
