import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';

import { FormEventHandler, useEffect, useState } from 'react'

import styles from '../styles/Home.module.scss'


type Data = {
  id: number;
  title: string;
  image: string;
  link: string;
  requirente: string;
};

const Home: NextPage = () => {

  const [products, setProducts] = useState<Data[]>([]);
  const [productsSelecteds, setProductsSelecteds] = useState<number[]>([]);
  const [nome, setNome] = useState<string>('');
  const [sending, setSending] = useState<boolean>(false);

  const selectProduct = (i: number) => {
    if (productsSelecteds.includes(i)) {
      const copy = productsSelecteds;
      copy.splice(productsSelecteds.indexOf(i), 1);
      setProductsSelecteds([...copy]);
    } else {
      setProductsSelecteds([...productsSelecteds, i]);
    }
  }

  const formSend:FormEventHandler = async (evt) => {
    evt.preventDefault();

    if (!sending) {

      for (const productIndex of productsSelecteds) {
        const product = products[productIndex];

        const result = await fetch('/api/presente/enviar', {
          method: 'POST',
          body: JSON.stringify({
            'nome': nome,
            'id': product.id
          })
        });

        setSending(false);
      }
      setSending(true);
    }

  }

  useEffect(() => {
    fetch('/api/presente')
      .then(async response => {
        const products = await response.json();

        setProducts(products.map((product: any) => ({
          id: product.ID,
          title: product.TITULO,
          image: product.IMAGEM,
          link: product.LINK,
          requirente: product.REQUIRENTE
        })));
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chá da Cecília</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous"></link>
      </Head>

      <div style={{textAlign: 'center'}}>
        <img src="images/photo.jpeg" className={ styles.foto } />
      </div>

      <div className="container-fluid">
        <div className="row">
      
          <div className="col-12">
            <h1 className="text-center m-3">
              Bem vindo ao Chá de bebê da Cecília
            </h1>
          </div>
      
          <div className="col-12">
            <form onSubmit={ formSend }>

              <div className={styles.fixOnTop}>
                <div className="form-group m-2">
                  <label>
                    Informe seu nome
                  </label>
                  <input 
                    onKeyUp={(evt) => setNome(evt.currentTarget.value)}
                    defaultValue={nome}
                    type="text" 
                    name="name" 
                    className="form-control" />
                </div>

                <p>
                  Abaixo selecionamos preparamos uma lista com os itens que precisamos. 
                </p>

                <div className="card">
                  <div className="card-body">
                    <strong> 
                      Seus presentes
                    </strong>
                    <ul>
                      { productsSelecteds.map(product => {
                        const p = products[product];
                        return <li key={product}>
                          { p.title } - <Link href={ p.link }><a target={"_blank"}> Comprar </a></Link>
                        </li>
                      })}
                    </ul>

                    <button className='btn btn-default' type="submit">
                      Enviar
                    </button>

                  </div>
                </div>
              </div>
      
              <div className={ styles.produtos }>
                {
                  products.map ((product, i) => 
                    <div className="produto" 
                      key={ i } 
                      data-active={ productsSelecteds.includes(i) }
                      onClick={ (evt) => {
                        selectProduct(i);
                        evt.stopPropagation();
                        evt.preventDefault();
                      } }
                    >
                      <label>
                        <img src={ product.image } alt={ product.title } />
                      </label>
                    </div>
                  )
                }
              </div>

      
            </form>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
