import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';

import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.scss'

type Data = {
  id: number;
  title: string;
  image: string;
  link: string;
};

const Home: NextPage = () => {

  const [products, setProducts] = useState<Data[]>([]);
  const [productsSelecteds, setProductsSelecteds] = useState<number[]>([]);

  const selectProduct = (i: number) => {
    if (productsSelecteds.includes(i)) {
      const copy = productsSelecteds;
      copy.splice(productsSelecteds.indexOf(i), 1);
      setProductsSelecteds([...copy]);
    } else {
      setProductsSelecteds([...productsSelecteds, i]);
    }
  }

  useEffect(() => {
    fetch('/api/presente')
      .then(async response => {
        setProducts(await response.json());
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous"></link>
      </Head>

      <div style={{textAlign: 'center'}}>
        <img src="images/photo.jpeg" className={ styles.foto } />
      </div>

      <div className="container-fluid">
        <div className="row">
      
          <div className="col-12">
            <h1 className="text-center m-3">
              Bem vindo ao Chá de bebê da Cecília
            </h1>
          </div>
      
          <div className="col-12">
            <form action="">

              <div className={styles.fixOnTop}>
                <div className="form-group m-2">
                  <label>
                    Informe seu nome
                  </label>
                  <input type="text" name="name" className="form-control" />
                </div>

                <p>
                  Abaixo selecionamos preparamos uma lista com os itens que precisamos. 
                </p>

                <div className="card">
                  <div className="card-body">
                    <strong> 
                      Seus presentes
                    </strong>
                    <ul>
                      { productsSelecteds.map(product => {
                        const p = products[product];
                        return <li key={product}>
                          { p.title } - <Link href={ p.link }><a target={"_blank"}> Comprar </a></Link>
                        </li>
                      })}
                    </ul>

                    <button className='btn btn-default'>
                      Enviar
                    </button>

                  </div>
                </div>
              </div>
      
              <div className={ styles.produtos }>
                {
                  products.map ((product, i) => 
                    <div className="produto" 
                      key={ i } 
                      data-active={ productsSelecteds.includes(i) }
                      onClick={ (evt) => {
                        selectProduct(i);
                        evt.stopPropagation();
                        evt.preventDefault();
                      } }
                    >
                      <label>
                        <img src={ product.image } alt={ product.title } />
                      </label>
                    </div>
                  )
                }
              </div>

      
            </form>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
